services:
    desktop:
        image: 'kasmweb/desktop:1.16.0'
        environment:
            - VNC_PW=password
        ports:
            - '6901:6901'
        shm_size: 1024m
        stdin_open: true

