---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:arch-xfce
    container_name: webtop-arch-xfce
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/Docker/webtop/data:/rootfs
    ports:
      - 37079:3000
      - 32848:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute,video,graphics,utility]
