---
services:
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - D:/Docker/phpmyadmin/config:/config
    ports:
      - 20938:80
    restart: unless-stopped
