services:
    tududi:
        environment:
            - TUDUDI_USER_EMAIL=admin@domain.com
            - TUDUDI_USER_PASSWORD=admin
            - TUDUDI_SESSION_SECRET=3337c138d17ac7acefa412e5db0d7ef6540905b198cc28c5bf0d11e48807a71bdfe48d82ed0a0a6eb667c937cbdd1db3e1e6073b3148bff37f73cc6398a39671 #long string of characters.
            - TUDUDI_INTERNAL_SSL_ENABLED=false
        volumes:
            - ~/Docker/tududi/data:/usr/src/app/tududi_db
        ports:
            - 3838:9292
        image: chrisvel/tududi:latest

## NOTE: Sept 24, 2024 - This docker-compose is NOT official and may not work in the future.
